server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lianxi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #   url:jdbc:mysql://58.87.85.198/lianxi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wang1993
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:



#mp配置
mybatis-plus:
  global-config:
    #数据库类型
    db-config:
      db-type: mysql
      logic-delete-value: true # 逻辑已删除值(默认为 1)
      logic-not-delete-value: false # 逻辑未删除值(默认为 0)
    #开启缓存使用@SqlParse来过滤saas拦截
    sql-parser-cache: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**.xml
logging:
  config:classpath: logback-spring.xml